services:
  api:
    build: api
    ports:
      - 4000:4000
    restart:
      always
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 4000
      MYSQL_DATABASE: blogs
      MYSQL_USER: nodeapp
      MYSQL_PASSWORD: 12345
      MYSQL_HOST: db
  front:
    build: front
    ports:
      - 3000:3000
    restart:
      always
    depends_on: 
      - api
    environment:
      API_URL: "http://api:4000"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogs
      MYSQL_USER: nodeapp
      MYSQL_PASSWORD: 12345
      MYSQL_HOST: "*"
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes: 
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  data:


